name: cypress formation udemy 1    // nom du workflow

on: push   

jobs:

  cypress-run:   
    runs-on: windows-latest   // Spécifie l'environnement d'exécution (Windows)
    steps:   
      - name: Checkout repository   // Étape pour récupérer le code du dépôt sur l'environnement d'exécution
        uses: actions/checkout@v4   // Utilise l'action officielle pour le checkout

      - name: Run Cypress tests   // Étape pour exécuter les tests Cypress
        uses: cypress-io/github-action@v6   // Utilise l'action officielle de Cypress pour installer le dépendances et exécuter les tests